# -*- coding: utf-8 -*-
"""tic reto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Y3FRLK94OdAKYP4ve9R5SWYzHXNyfi8
"""

def bisiesto(num):
  if num % 4 == 0 and (num % 100 != 0 or num % 400 == 0): # esto sirve para sabere si es bisiesto o no
    altramuces=True
  else:
    altramuces=False

  return altramuces #he llamado la variable altramuces porque roberto me lo dijo

def calcular_dia(D,M,A,is_bisiesto):
  dic={0:'domingo',1:'lunes',2:'martes',3:'miércoles',4:'jueves',5:'viernes',6:'sábado'}
  modulo_bisiesto={1:0,2:3,3:4,4:0,5:2,6:5,7:0,8:3,9:6,10:1,11:4,12:6}
  modulo_nobisiesto={1:0,2:3,3:3,4:6,5:1,6:4,7:6,8:2,9:5,10:0,11:3,12:5}
  if is_bisiesto==True:
    M_=modulo_bisiesto[M]
  else:
    M_=modulo_nobisiesto[M]

  #esta fórmula está copiada de https://es.wikibooks.org/wiki/Algoritmia/Algoritmo_para_calcular_el_d%C3%ADa_de_la_semana

  x= ( int((A-1)/4) - (3 * int((int((A-1)/100) + 1)/4)))%7 

  dia_semana=((A-1)%7 + x + M_ + D%7)%7

  dia_semana=dic[dia_semana]
  return dia_semana

fin=False

while not fin:
  # pido los datos
  dia=input('Ingrese el día: ')
  mes=input('Ingrese el mes: ')
  año=input('Ingrese el años: ')

  # hago todas las validaciones de datos
  try:
    dia=int(dia);mes=int(mes);año=int(año)
    es_bisiesto=bisiesto(año)
    if año>0:
      if es_bisiesto==True:
        if mes<=12:
          if mes==2:
            if dia<=29:
              fin=True
            else:
              print(f'Un mes no puede tener {dia} días')  
          else:
            if dia<=31:
              fin=True
            else:
              print(f'Un mes no puede tener {dia} días')
              fin=False
        else:
          print(f'Un año no puede tener {mes} meses')
          fin=False 
      else:
        if mes<=12:
          if dia<=31:
            fin=True

          else:
            print(f'Un mes no puede tener {dia} días')
            fin=False

        else:
          print(f'Un año no puede tener {mes} meses')
          fin=False

  except:
    print("El número de dia/mes/año debe de ser un número real")

dia_semana=calcular_dia(dia,mes,año,bisiesto(año)) # para calcular el día
print('')
print(f'El día {dia}/{mes}/{año} es {dia_semana}')